# Generated by Django 4.2.3 on 2024-04-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_itemstatus_itemtype_remove_item_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
