# Generated by Django 4.2.3 on 2024-04-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_item_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='deviceSerialNumber',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
