# Generated by Django 4.2.3 on 2024-04-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_remove_item_id_alter_item_deviceserialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='deviceSerialNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
