# Generated by Django 4.2.3 on 2024-04-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_alter_booking_end_date_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
