# Generated by Django 4.2.3 on 2024-04-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0011_booking_end_time_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
