# Generated by Django 4.2.3 on 2024-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0012_item_is_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_overdue',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
